project:
  type: book

book:
  title: "Python Essence"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/py-essense
  site-url: https://py-essense-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: OOP
      chapters: 
        - text: Protocol vs ABC
          href: "contents/oop/protocols-vs-abc.qmd"
    - part: Tests
      chapters: 
        - text: Pytest Basics
          href: "contents/tests/pytests-basic.qmd"
    - part: Packages
      chapters: 
        - text: "__main__.py"
          href: "contents/packages/__main__.qmd"
    - part: CLI
      chapters: 
        - text: argparse Funda
          href: "contents/cli/argparse-funda.qmd"

format:
  html:
    theme:
      light:
        - theme/warm-light.scss
      dark:
        - theme/warm-dark.scss
    highlight-style:
      light: theme/atom-one-light-warm.theme
      dark: theme/atom-one-dark-warm.theme
    toc-depth: 4

freeze: auto
